# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\liceu\lesson.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Lesson(object):
    def setupUi(self, Lesson):
        Lesson.setObjectName("Lesson")
        Lesson.resize(733, 496)
        self.label = QtWidgets.QLabel(Lesson)
        self.label.setGeometry(QtCore.QRect(0, 0, 731, 491))
        self.label.setText("")
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setPixmap(QtGui.QPixmap("C:/Users/vladh/PycharmProjects/dotwork/1.PNG"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Lesson)
        QtCore.QMetaObject.connectSlotsByName(Lesson)

    def retranslateUi(self, Lesson):
        _translate = QtCore.QCoreApplication.translate
        Lesson.setWindowTitle(_translate("Lesson", "Lesson"))



